import type { LspServerConfig } from "./types";

export const LSP_INSTALL_HINTS: Readonly<Record<string, string>> = {
	bash: "npm install -g bash-language-server",
	"bash-ls": "npm install -g bash-language-server",
	biome: "npm install -g @biomejs/biome",
	basedpyright: "pip install basedpyright",
	clangd: "See https://clangd.llvm.org/installation",
	"clojure-lsp": "See https://clojure-lsp.io/installation/",
	csharp: "dotnet tool install -g csharp-ls",
	dart: "Included with Dart SDK",
	deno: "Install Deno from https://deno.land",
	dockerfile: "npm install -g dockerfile-language-server-nodejs",
	"elixir-ls": "See https://github.com/elixir-lsp/elixir-ls",
	eslint: "npm install -g vscode-langservers-extracted",
	fsharp: "dotnet tool install -g fsautocomplete",
	gleam: "See https://gleam.run/getting-started/installing/",
	gopls: "go install golang.org/x/tools/gopls@latest",
	"haskell-language-server": "ghcup install hls",
	jdtls: "See https://github.com/eclipse-jdtls/eclipse.jdt.ls",
	"kotlin-ls": "See https://github.com/Kotlin/kotlin-lsp",
	"lua-ls": "See https://github.com/LuaLS/lua-language-server",
	nixd: "nix profile install nixpkgs#nixd",
	"ocaml-lsp": "opam install ocaml-lsp-server",
	oxlint: "npm install -g oxlint",
	php: "npm install -g intelephense",
	prisma: "npm install -g prisma",
	pyright: "pip install pyright",
	"ruby-lsp": "gem install ruby-lsp",
	ruff: "pip install ruff",
	rust: "rustup component add rust-analyzer",
	"sourcekit-lsp": "Included with Xcode or Swift toolchain",
	svelte: "npm install -g svelte-language-server",
	terraform: "See https://github.com/hashicorp/terraform-ls",
	"terraform-ls": "See https://github.com/hashicorp/terraform-ls",
	texlab: "See https://github.com/latex-lsp/texlab",
	tinymist: "See https://github.com/Myriad-Dreamin/tinymist",
	typescript: "npm install -g typescript-language-server typescript",
	ty: "pip install ty",
	vue: "npm install -g @vue/language-server",
	"yaml-ls": "npm install -g yaml-language-server",
	zls: "See https://github.com/zigtools/zls",
};

export const BUILTIN_SERVERS: Readonly<Record<string, Omit<LspServerConfig, "id">>> = {
	astro: { command: ["astro-ls", "--stdio"], extensions: [".astro"] },
	bash: {
		command: ["bash-language-server", "start"],
		extensions: [".sh", ".bash", ".zsh", ".ksh"],
	},
	"bash-ls": {
		command: ["bash-language-server", "start"],
		extensions: [".sh", ".bash", ".zsh", ".ksh"],
	},
	biome: {
		command: ["biome", "lsp-proxy", "--stdio"],
		extensions: [
			".ts",
			".tsx",
			".js",
			".jsx",
			".mjs",
			".cjs",
			".mts",
			".cts",
			".json",
			".jsonc",
			".vue",
			".astro",
			".svelte",
			".css",
			".graphql",
			".gql",
			".html",
		],
	},
	basedpyright: { command: ["basedpyright-langserver", "--stdio"], extensions: [".py", ".pyi"] },
	clangd: {
		command: ["clangd", "--background-index", "--clang-tidy"],
		extensions: [".c", ".cpp", ".cc", ".cxx", ".c++", ".h", ".hpp", ".hh", ".hxx", ".h++"],
	},
	"clojure-lsp": {
		command: ["clojure-lsp", "listen"],
		extensions: [".clj", ".cljs", ".cljc", ".edn"],
	},
	csharp: { command: ["csharp-ls"], extensions: [".cs"] },
	dart: { command: ["dart", "language-server", "--lsp"], extensions: [".dart"] },
	deno: { command: ["deno", "lsp"], extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs"] },
	dockerfile: { command: ["docker-langserver", "--stdio"], extensions: [".dockerfile"] },
	"elixir-ls": { command: ["elixir-ls"], extensions: [".ex", ".exs"] },
	eslint: {
		command: ["vscode-eslint-language-server", "--stdio"],
		extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".mts", ".cts", ".vue"],
	},
	fsharp: { command: ["fsautocomplete"], extensions: [".fs", ".fsi", ".fsx", ".fsscript"] },
	gleam: { command: ["gleam", "lsp"], extensions: [".gleam"] },
	gopls: { command: ["gopls"], extensions: [".go"] },
	"haskell-language-server": {
		command: ["haskell-language-server-wrapper", "--lsp"],
		extensions: [".hs", ".lhs"],
	},
	jdtls: { command: ["jdtls"], extensions: [".java"] },
	"kotlin-ls": { command: ["kotlin-lsp"], extensions: [".kt", ".kts"] },
	"lua-ls": { command: ["lua-language-server"], extensions: [".lua"] },
	nixd: { command: ["nixd"], extensions: [".nix"] },
	"ocaml-lsp": { command: ["ocamllsp"], extensions: [".ml", ".mli"] },
	oxlint: {
		command: ["oxlint", "--lsp"],
		extensions: [
			".ts",
			".tsx",
			".js",
			".jsx",
			".mjs",
			".cjs",
			".mts",
			".cts",
			".vue",
			".astro",
			".svelte",
		],
	},
	php: { command: ["intelephense", "--stdio"], extensions: [".php"] },
	prisma: { command: ["prisma", "language-server"], extensions: [".prisma"] },
	pyright: { command: ["pyright-langserver", "--stdio"], extensions: [".py", ".pyi"] },
	"ruby-lsp": { command: ["rubocop", "--lsp"], extensions: [".rb", ".rake", ".gemspec", ".ru"] },
	ruff: { command: ["ruff", "server"], extensions: [".py", ".pyi"] },
	rust: { command: ["rust-analyzer"], extensions: [".rs"] },
	"sourcekit-lsp": { command: ["sourcekit-lsp"], extensions: [".swift", ".objc", ".objcpp"] },
	svelte: { command: ["svelteserver", "--stdio"], extensions: [".svelte"] },
	terraform: { command: ["terraform-ls", "serve"], extensions: [".tf", ".tfvars"] },
	"terraform-ls": { command: ["terraform-ls", "serve"], extensions: [".tf", ".tfvars"] },
	texlab: { command: ["texlab"], extensions: [".tex", ".bib"] },
	tinymist: { command: ["tinymist"], extensions: [".typ", ".typc"] },
	typescript: {
		command: ["typescript-language-server", "--stdio"],
		extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".mts", ".cts"],
	},
	ty: { command: ["ty", "server"], extensions: [".py", ".pyi"] },
	vue: { command: ["vue-language-server", "--stdio"], extensions: [".vue"] },
	"yaml-ls": { command: ["yaml-language-server", "--stdio"], extensions: [".yaml", ".yml"] },
	zls: { command: ["zls"], extensions: [".zig", ".zon"] },
};
