import type { LspCapability, LspServerConfig } from "./types";

const FULL_CAPABILITIES: readonly LspCapability[] = [
	"diagnostics",
	"definition",
	"references",
	"symbols",
	"rename",
	"hover",
];

const DIAGNOSTICS_AND_FORMATTING: readonly LspCapability[] = ["diagnostics", "formatting"];

const DIAGNOSTICS_ONLY: readonly LspCapability[] = ["diagnostics"];

export const LSP_INSTALL_HINTS: Readonly<Record<string, string>> = {
	bash: "npm install -g bash-language-server",
	"bash-ls": "npm install -g bash-language-server",
	biome: "npm install -g @biomejs/biome",
	basedpyright: "pip install basedpyright",
	clangd: "See https://clangd.llvm.org/installation",
	"clojure-lsp": "See https://clojure-lsp.io/installation/",
	csharp: "dotnet tool install -g csharp-ls",
	dart: "Included with Dart SDK",
	deno: "Install Deno from https://deno.land",
	dockerfile: "npm install -g dockerfile-language-server-nodejs",
	"elixir-ls": "See https://github.com/elixir-lsp/elixir-ls",
	eslint: "npm install -g vscode-langservers-extracted",
	fsharp: "dotnet tool install -g fsautocomplete",
	gleam: "See https://gleam.run/getting-started/installing/",
	gopls: "go install golang.org/x/tools/gopls@latest",
	"haskell-language-server": "ghcup install hls",
	jdtls: "See https://github.com/eclipse-jdtls/eclipse.jdt.ls",
	"kotlin-ls": "See https://github.com/Kotlin/kotlin-lsp",
	"lua-ls": "See https://github.com/LuaLS/lua-language-server",
	nixd: "nix profile install nixpkgs#nixd",
	"ocaml-lsp": "opam install ocaml-lsp-server",
	oxlint: "npm install -g oxlint",
	php: "npm install -g intelephense",
	prisma: "npm install -g prisma",
	pyright: "pip install pyright",
	"ruby-lsp": "gem install ruby-lsp",
	ruff: "pip install ruff",
	rust: "rustup component add rust-analyzer",
	"sourcekit-lsp": "Included with Xcode or Swift toolchain",
	svelte: "npm install -g svelte-language-server",
	terraform: "See https://github.com/hashicorp/terraform-ls",
	"terraform-ls": "See https://github.com/hashicorp/terraform-ls",
	texlab: "See https://github.com/latex-lsp/texlab",
	tinymist: "See https://github.com/Myriad-Dreamin/tinymist",
	typescript: "npm install -g typescript-language-server typescript",
	ty: "pip install ty",
	vue: "npm install -g @vue/language-server",
	"yaml-ls": "npm install -g yaml-language-server",
	zls: "See https://github.com/zigtools/zls",
};

export const BUILTIN_SERVERS: Readonly<Record<string, Omit<LspServerConfig, "id">>> = {
	astro: {
		capabilities: FULL_CAPABILITIES,
		command: ["astro-ls", "--stdio"],
		extensions: [".astro"],
	},
	bash: {
		capabilities: FULL_CAPABILITIES,
		command: ["bash-language-server", "start"],
		extensions: [".sh", ".bash", ".zsh", ".ksh"],
	},
	"bash-ls": {
		capabilities: FULL_CAPABILITIES,
		command: ["bash-language-server", "start"],
		extensions: [".sh", ".bash", ".zsh", ".ksh"],
	},
	biome: {
		capabilities: DIAGNOSTICS_AND_FORMATTING,
		command: ["biome", "lsp-proxy", "--stdio"],
		extensions: [
			".ts",
			".tsx",
			".js",
			".jsx",
			".mjs",
			".cjs",
			".mts",
			".cts",
			".json",
			".jsonc",
			".vue",
			".astro",
			".svelte",
			".css",
			".graphql",
			".gql",
			".html",
		],
	},
	basedpyright: {
		capabilities: FULL_CAPABILITIES,
		command: ["basedpyright-langserver", "--stdio"],
		extensions: [".py", ".pyi"],
	},
	clangd: {
		capabilities: FULL_CAPABILITIES,
		command: ["clangd", "--background-index", "--clang-tidy"],
		extensions: [".c", ".cpp", ".cc", ".cxx", ".c++", ".h", ".hpp", ".hh", ".hxx", ".h++"],
	},
	"clojure-lsp": {
		capabilities: FULL_CAPABILITIES,
		command: ["clojure-lsp", "listen"],
		extensions: [".clj", ".cljs", ".cljc", ".edn"],
	},
	csharp: { capabilities: FULL_CAPABILITIES, command: ["csharp-ls"], extensions: [".cs"] },
	dart: {
		capabilities: FULL_CAPABILITIES,
		command: ["dart", "language-server", "--lsp"],
		extensions: [".dart"],
	},
	deno: {
		capabilities: FULL_CAPABILITIES,
		command: ["deno", "lsp"],
		extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs"],
	},
	dockerfile: {
		capabilities: FULL_CAPABILITIES,
		command: ["docker-langserver", "--stdio"],
		extensions: [".dockerfile"],
	},
	"elixir-ls": {
		capabilities: FULL_CAPABILITIES,
		command: ["elixir-ls"],
		extensions: [".ex", ".exs"],
	},
	eslint: {
		capabilities: DIAGNOSTICS_ONLY,
		command: ["vscode-eslint-language-server", "--stdio"],
		extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".mts", ".cts", ".vue"],
	},
	fsharp: {
		capabilities: FULL_CAPABILITIES,
		command: ["fsautocomplete"],
		extensions: [".fs", ".fsi", ".fsx", ".fsscript"],
	},
	gleam: { capabilities: FULL_CAPABILITIES, command: ["gleam", "lsp"], extensions: [".gleam"] },
	gopls: { capabilities: FULL_CAPABILITIES, command: ["gopls"], extensions: [".go"] },
	"haskell-language-server": {
		capabilities: FULL_CAPABILITIES,
		command: ["haskell-language-server-wrapper", "--lsp"],
		extensions: [".hs", ".lhs"],
	},
	jdtls: { capabilities: FULL_CAPABILITIES, command: ["jdtls"], extensions: [".java"] },
	"kotlin-ls": {
		capabilities: FULL_CAPABILITIES,
		command: ["kotlin-lsp"],
		extensions: [".kt", ".kts"],
	},
	"lua-ls": {
		capabilities: FULL_CAPABILITIES,
		command: ["lua-language-server"],
		extensions: [".lua"],
	},
	nixd: { capabilities: FULL_CAPABILITIES, command: ["nixd"], extensions: [".nix"] },
	"ocaml-lsp": {
		capabilities: FULL_CAPABILITIES,
		command: ["ocamllsp"],
		extensions: [".ml", ".mli"],
	},
	oxlint: {
		capabilities: DIAGNOSTICS_ONLY,
		command: ["oxlint", "--lsp"],
		extensions: [
			".ts",
			".tsx",
			".js",
			".jsx",
			".mjs",
			".cjs",
			".mts",
			".cts",
			".vue",
			".astro",
			".svelte",
		],
	},
	php: {
		capabilities: FULL_CAPABILITIES,
		command: ["intelephense", "--stdio"],
		extensions: [".php"],
	},
	prisma: {
		capabilities: FULL_CAPABILITIES,
		command: ["prisma", "language-server"],
		extensions: [".prisma"],
	},
	pyright: {
		capabilities: FULL_CAPABILITIES,
		command: ["pyright-langserver", "--stdio"],
		extensions: [".py", ".pyi"],
	},
	"ruby-lsp": {
		capabilities: FULL_CAPABILITIES,
		command: ["rubocop", "--lsp"],
		extensions: [".rb", ".rake", ".gemspec", ".ru"],
	},
	ruff: {
		capabilities: DIAGNOSTICS_ONLY,
		command: ["ruff", "server"],
		extensions: [".py", ".pyi"],
	},
	rust: { capabilities: FULL_CAPABILITIES, command: ["rust-analyzer"], extensions: [".rs"] },
	"sourcekit-lsp": {
		capabilities: FULL_CAPABILITIES,
		command: ["sourcekit-lsp"],
		extensions: [".swift", ".objc", ".objcpp"],
	},
	svelte: {
		capabilities: FULL_CAPABILITIES,
		command: ["svelteserver", "--stdio"],
		extensions: [".svelte"],
	},
	terraform: {
		capabilities: FULL_CAPABILITIES,
		command: ["terraform-ls", "serve"],
		extensions: [".tf", ".tfvars"],
	},
	"terraform-ls": {
		capabilities: FULL_CAPABILITIES,
		command: ["terraform-ls", "serve"],
		extensions: [".tf", ".tfvars"],
	},
	texlab: { capabilities: FULL_CAPABILITIES, command: ["texlab"], extensions: [".tex", ".bib"] },
	tinymist: {
		capabilities: FULL_CAPABILITIES,
		command: ["tinymist"],
		extensions: [".typ", ".typc"],
	},
	typescript: {
		capabilities: FULL_CAPABILITIES,
		command: ["typescript-language-server", "--stdio"],
		extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".mts", ".cts"],
	},
	ty: { capabilities: FULL_CAPABILITIES, command: ["ty", "server"], extensions: [".py", ".pyi"] },
	vue: {
		capabilities: FULL_CAPABILITIES,
		command: ["vue-language-server", "--stdio"],
		extensions: [".vue"],
	},
	"yaml-ls": {
		capabilities: FULL_CAPABILITIES,
		command: ["yaml-language-server", "--stdio"],
		extensions: [".yaml", ".yml"],
	},
	zls: { capabilities: FULL_CAPABILITIES, command: ["zls"], extensions: [".zig", ".zon"] },
};
